spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_chatroom?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Sq66+66=66
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml

logging:
  file:
    name: /var/log/java_chatroom/chatroom.log  # 完整日志文件路径
    level:
      root: INFO  # 全局日志级别
      com.example.chatroom: DEBUG  # 替换为您的实际包名
      org.springframework.web: INFO
      org.hibernate: WARN
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){green} %clr(%logger{36}){cyan} - %msg%n"
  pattern:
    console: "[%-5level] - %msg%n"